UPDATE public.faqs SET question_en = 'How much does a brochure website cost?', answer_en = 'A professional brochure website typically costs between €1,500 and €5,000, depending on the number of pages, the level of customization, and the features you need (contact form, gallery, blog, etc.). A five-page site with a bespoke design and basic SEO optimization usually falls in the €2,500–€3,500 range. This price includes graphic design, development, content integration, and go-live. I recommend defining your requirements clearly upfront so you can get an accurate quote and avoid surprises.', category_en = 'Pricing & Budget' WHERE id = 'd2ef8622-1bd6-4cea-bf65-bb62582a1a81';

UPDATE public.faqs SET question_es = '¿Cuánto cuesta una página web corporativa?', answer_es = 'Una página web corporativa profesional suele costar entre 1.500 € y 5.000 €, según el número de páginas, el nivel de personalización y las funcionalidades deseadas (formulario de contacto, galería, blog, etc.). Un sitio de 5 páginas con diseño a medida y optimización SEO básica ronda los 2.500 € a 3.500 €. Esta tarifa incluye el diseño gráfico, el desarrollo, la integración del contenido y la puesta en línea. Le recomiendo definir claramente sus necesidades de antemano para obtener un presupuesto preciso y evitar sorpresas.', category_es = 'Tarifas y Presupuesto' WHERE id = 'd2ef8622-1bd6-4cea-bf65-bb62582a1a81';

UPDATE public.faqs SET question_en = 'How much does an e-commerce site cost?', answer_en = 'A bespoke e-commerce site is an investment of €3,000 to €15,000 depending on complexity: number of products, payment gateway, stock management, shipping, customer area, etc. For an online store with fewer than 50 products using Stripe or PayPal, expect roughly €4,000 to €7,000. More complex setups with multi-currency management, subscriptions, or marketplaces often exceed €10,000. The key is to choose a scalable architecture that can grow with your business.', category_en = 'Pricing & Budget' WHERE id = 'ef987f27-ebd6-46c0-ba2e-f400def2c8ca';

UPDATE public.faqs SET question_es = '¿Cuánto cuesta una tienda online?', answer_es = 'Una tienda online a medida supone una inversión de 3.000 € a 15.000 € según la complejidad: número de productos, pasarela de pago, gestión de stock, envíos, área de cliente, etc. Para una tienda con menos de 50 productos con Stripe o PayPal, cuente entre 4.000 € y 7.000 €. Las soluciones más complejas con gestión multidivisa, suscripciones o marketplace suelen superar los 10.000 €. Lo importante es elegir una arquitectura escalable que pueda crecer con su actividad.', category_es = 'Tarifas y Presupuesto' WHERE id = 'ef987f27-ebd6-46c0-ba2e-f400def2c8ca';

UPDATE public.faqs SET question_en = 'How much does a custom web application cost?', answer_en = 'The cost of a custom web application starts from around €5,000 and can reach €30,000 or more depending on functional complexity. A simple internal management tool typically falls in the €5,000–€10,000 range, whereas a full SaaS platform with authentication, dashboards, and APIs requires a budget of €15,000 to €30,000. Every project is unique: I first produce a detailed specification to estimate development time accurately. An MVP (minimum viable product) often lets you start with a controlled budget and iterate from there.', category_en = 'Pricing & Budget' WHERE id = '077ec11e-22af-4411-bbfe-8165de04ebd3';

UPDATE public.faqs SET question_es = '¿Cuánto cuesta una aplicación web a medida?', answer_es = 'El coste de una aplicación web a medida parte de 5.000 € y puede alcanzar 30.000 € o más según la complejidad funcional. Una herramienta interna de gestión sencilla ronda los 5.000 € a 10.000 €, mientras que una plataforma SaaS completa con autenticación, paneles de control y API requiere un presupuesto de 15.000 € a 30.000 €. Cada proyecto es único: primero elaboro un pliego de condiciones detallado para estimar con precisión el tiempo de desarrollo. Un MVP (producto mínimo viable) permite a menudo empezar con un presupuesto controlado e iterar después.', category_es = 'Tarifas y Presupuesto' WHERE id = '077ec11e-22af-4411-bbfe-8165de04ebd3';

UPDATE public.faqs SET question_en = 'What are the recurring costs of a website?', answer_en = 'Annual website costs include hosting (€50–€300/year depending on the solution), domain name (€10–€20/year), SSL certificate (often free with Let''s Encrypt), and optional technical maintenance (€200–€1,200/year). If you use third-party tools such as a newsletter or CRM, budget for additional subscriptions. I recommend an annual budget of €500–€1,500 to keep a professional site fast and secure. It is a modest investment compared to the visibility it brings you.', category_en = 'Pricing & Budget' WHERE id = 'abaa6464-89cf-4765-a07f-aacabfec1443';

UPDATE public.faqs SET question_es = '¿Cuáles son los costes recurrentes de un sitio web?', answer_es = 'Los costes anuales de un sitio web incluyen el alojamiento (50 € a 300 €/año según la solución), el nombre de dominio (10 € a 20 €/año), el certificado SSL (a menudo gratuito con Let''s Encrypt) y, si procede, el mantenimiento técnico (200 € a 1.200 €/año). Si utiliza herramientas de terceros como un boletín o un CRM, prevea suscripciones adicionales. Recomiendo un presupuesto anual de 500 € a 1.500 € para mantener un sitio profesional eficiente y seguro. Es una inversión modesta comparada con la visibilidad que le aporta.', category_es = 'Tarifas y Presupuesto' WHERE id = 'abaa6464-89cf-4765-a07f-aacabfec1443';

UPDATE public.faqs SET question_en = 'Do you offer payment plans?', answer_en = 'Yes, I offer staged payments in several installments to make your project more accessible. The usual pattern is a 30% deposit when you sign the quote, 40% when designs are approved, and 30% on final delivery. For larger projects, payment in three or four monthly installments can be arranged. The goal is to find an arrangement that works for you while keeping the project running smoothly. Feel free to discuss this during our first conversation.', category_en = 'Pricing & Budget' WHERE id = 'f3db6e03-5904-4a19-a9bf-0aadfcbc098a';

UPDATE public.faqs SET question_es = '¿Ofrece facilidades de pago?', answer_es = 'Sí, propongo fraccionar el pago en varias veces para hacer su proyecto más accesible. El esquema habitual es un anticipo del 30 % al firmar el presupuesto, un 40 % en la validación de las maquetas y un 30 % en la entrega final. Para proyectos más grandes, se puede plantear el pago en 3 o 4 mensualidades. El objetivo es encontrar un acuerdo que le convenga y permita un desarrollo fluido del proyecto. No dude en hablarlo en nuestro primer contacto.', category_es = 'Tarifas y Presupuesto' WHERE id = 'f3db6e03-5904-4a19-a9bf-0aadfcbc098a';

UPDATE public.faqs SET question_en = 'Why does a bespoke site cost more than a template?', answer_en = 'A bespoke site is designed specifically for your business, brand identity, and goals. Unlike a pre-made template, every element is crafted to optimize your visitors'' experience and your conversion rate. The code is cleaner, faster, and easier to evolve. A template may look cheap upfront, but hidden customization costs, functional limits, and performance issues often end up exceeding the investment of a bespoke site. It is an investment in long-term quality and sustainability.', category_en = 'Pricing & Budget' WHERE id = '586ab60f-e678-4707-a1cb-b5aec722e6fe';

UPDATE public.faqs SET question_es = '¿Por qué un sitio a medida cuesta más que una plantilla?', answer_es = 'Un sitio a medida está pensado específicamente para su actividad, su identidad visual y sus objetivos de negocio. A diferencia de una plantilla prefabricada, cada elemento está diseñado para optimizar la experiencia de sus visitantes y su tasa de conversión. El código es más limpio, más rápido y más fácil de hacer evolucionar. Una plantilla puede parecer económica al principio, pero los costes ocultos de personalización, las limitaciones funcionales y los problemas de rendimiento suelen acabar superando la inversión de un sitio a medida. Es una apuesta por la durabilidad y la calidad.', category_es = 'Tarifas y Presupuesto' WHERE id = '586ab60f-e678-4707-a1cb-b5aec722e6fe';

UPDATE public.faqs SET question_en = 'How much does website maintenance cost?', answer_en = 'Website maintenance typically costs between €50 and €200 per month depending on the service level. A basic package includes security updates, regular backups, and uptime monitoring. A premium package adds content updates, performance optimization, and priority support. Without maintenance, your site becomes vulnerable to security issues and may lose performance over time. I recommend at least quarterly follow-up to keep your site secure and running well.', category_en = 'Pricing & Budget' WHERE id = '65126f28-db3e-4db9-b65a-df75035287a1';

UPDATE public.faqs SET question_es = '¿Cuánto cuesta el mantenimiento de un sitio web?', answer_es = 'El mantenimiento de un sitio web cuesta entre 50 € y 200 € al mes según el nivel de servicio. Un paquete básico incluye actualizaciones de seguridad, copias de seguridad periódicas y supervisión de la disponibilidad. Un paquete premium añade cambios de contenido, optimización del rendimiento y soporte prioritario. Sin mantenimiento, su sitio se vuelve vulnerable a fallos de seguridad y puede perder rendimiento con el tiempo. Recomiendo al menos un seguimiento trimestral para garantizar el buen funcionamiento y la seguridad de su sitio.', category_es = 'Tarifas y Presupuesto' WHERE id = '65126f28-db3e-4db9-b65a-df75035287a1';

UPDATE public.faqs SET question_en = 'Is the quote free?', answer_en = 'Yes, the quote is completely free and without obligation. After an initial conversation to understand your needs, I send you a detailed proposal covering project scope, planned features, estimated timeline, and budget. This document lets you compare offers transparently. I take the time to explain each line item so you know exactly what you are paying for. Feel free to get in touch even if your project is still at the idea stage.', category_en = 'Pricing & Budget' WHERE id = 'ec718b4d-4915-480e-afc1-985a5863ed54';

UPDATE public.faqs SET question_es = '¿El presupuesto es gratuito?', answer_es = 'Sí, el presupuesto es totalmente gratuito y sin compromiso. Tras un primer intercambio para entender sus necesidades, le envío una propuesta detallada con el alcance del proyecto, las funcionalidades previstas, el calendario estimado y el presupuesto. Este documento le permite comparar ofertas con total transparencia. Dedico tiempo a explicarle cada partida para que sepa exactamente en qué invierte. No dude en contactarme para hablarlo, aunque su proyecto esté aún en fase de reflexión.', category_es = 'Tarifas y Presupuesto' WHERE id = 'ec718b4d-4915-480e-afc1-985a5863ed54';

UPDATE public.faqs SET question_en = 'What exactly is included in the price of a brochure website?', answer_en = 'The price of a brochure website typically includes: a needs assessment, UX/UI design (wireframes and graphic mockups), front-end and back-end development, integration of your content, basic technical SEO, go-live, and testing across browsers and devices. Revisions are also included (usually two or three rounds of changes). Content writing, professional photography, and advanced SEO are additional services that can be added to the quote.', category_en = 'Pricing & Budget' WHERE id = 'f9f790f5-af45-464e-861d-ed64a8b447b4';

UPDATE public.faqs SET question_es = '¿Qué incluye exactamente el precio de una página web corporativa?', answer_es = 'El precio de una página web corporativa suele incluir: el análisis de sus necesidades, el diseño UX/UI (wireframes y maquetas gráficas), el desarrollo front-end y back-end, la integración de su contenido, la optimización SEO técnica básica, la puesta en línea y las pruebas en distintos navegadores y dispositivos. Las revisiones también están incluidas (normalmente 2 o 3 rondas de correcciones). En cambio, la redacción de contenidos, las sesiones de fotografía profesional y el posicionamiento avanzado son servicios complementarios que se pueden añadir al presupuesto.', category_es = 'Tarifas y Presupuesto' WHERE id = 'f9f790f5-af45-464e-861d-ed64a8b447b4';

UPDATE public.faqs SET question_en = 'Are the domain name and hosting included?', answer_en = 'The first year of domain and hosting can be included in the quote depending on the package chosen. A domain name (.fr, .com) costs roughly €10–€15 per year, and hosting ranges from €50 to €300 per year depending on performance needs. I advise you on the best domain and host for your project. After the first year, these recurring costs remain your responsibility, but I support you with renewals and you remain the owner of your domain.', category_en = 'Pricing & Budget' WHERE id = '7bbbcd1e-ae40-48f4-b38c-e52a347e9f7f';

UPDATE public.faqs SET question_es = '¿Están incluidos el nombre de dominio y el alojamiento?', answer_es = 'El primer año de nombre de dominio y alojamiento puede incluirse en el presupuesto según la fórmula elegida. El nombre de dominio (.fr, .com) cuesta aproximadamente 10 € a 15 € al año y el alojamiento entre 50 € y 300 € al año según el rendimiento necesario. Le asesoro sobre la mejor opción de dominio y alojamiento según su proyecto. Tras el primer año, estos gastos recurrentes corren a su cargo, pero le acompaño en los trámites de renovación y usted sigue siendo propietario de su dominio.', category_es = 'Tarifas y Presupuesto' WHERE id = '7bbbcd1e-ae40-48f4-b38c-e52a347e9f7f';
